import path from "path";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "@shared": path.resolve(__dirname, "../shared"),
    },
  },
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    include: [
      "src/**/*.{test,spec}.{ts,tsx}",
      "../shared/**/*.{test,spec}.{ts,tsx}",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      include: [
        "src/hooks/useModalDialog.ts",
        "src/hooks/useRovingTabs.ts",
        "src/lib/focusable.ts",
        "src/components/ui/SlidePanel.tsx",
        "src/components/feedback/ErrorMessage.tsx",
        "src/features/*/services/*.service.ts",
        "src/features/*/services/*.errors.ts",
        "src/features/*/services/*.mapper.ts",
        "src/features/*/services/*.schema.ts",
        "src/lib/errors.ts",
        "src/lib/result.ts",
        "src/lib/sse.ts",
        "src/lib/userMessages.ts",
        "src/lib/validation/**",
        "src/features/chat/utils/textCleaning.ts",
        "src/features/projects/utils/dragUtils.ts",
        "src/features/projects/utils/documentDisplay.tsx",
        "src/lib/store/sessionReset.ts",
        "src/lib/store/authStore.ts",
        "src/lib/store/topbarStore.ts",
        "src/features/projects/stores/pendingFolderUploadStore.ts",
        "src/features/projects/stores/uploadStore.ts",
        "src/features/projects/stores/selectionStore.ts",
        "src/features/projects/stores/projectsViewStore.ts",
        "src/features/admin/stores/store.ts",
        "src/pages/components/WorkspaceModals.tsx",
        "src/pages/components/workspaceContextMenuItems.tsx",
        "src/pages/components/DocumentModals.tsx",
        "src/pages/components/FolderModals.tsx",
        "src/pages/components/WorkspaceDocumentsTab.tsx",
        "src/pages/components/DocumentsToolbar.tsx",
        "src/pages/components/FolderBreadcrumb.tsx",
        "src/pages/components/DocumentsCollection.tsx",
        "src/pages/components/DocumentsSectionState.tsx",
        "src/pages/components/DocumentsPanel.tsx",
        "src/pages/hooks/useWorkspaceDocuments.ts",
        "src/pages/hooks/useUploadCleanup.ts",
        "src/pages/hooks/usePendingUploadDocs.ts",
        "src/pages/hooks/useSortedDocuments.ts",
        "src/pages/hooks/useDocumentsSummary.ts",
        "src/pages/hooks/useBatchDocumentActions.ts",
        "src/pages/hooks/useFolderSelection.ts",
        "src/features/admin/components/ChunkDetail.tsx",
        "src/features/admin/components/chunkContentTypeBadges.ts",
        "src/features/admin/components/ChunkDetailDisplay.tsx",
        "src/features/admin/components/ChunkDetailTextPanel.tsx",
        "src/features/admin/components/ChunkDetailActionBar.tsx",
        "src/features/admin/components/ChunkDetailRelatedChunks.tsx",
        "src/features/admin/hooks/useChunkDetailActions.ts",
        "src/features/admin/hooks/useChunkDetailEditState.ts",
        "src/features/admin/hooks/useChunkDetailMutations.ts",
        "src/features/admin/hooks/useChunkDetailSaveAndSplit.ts",
        "src/features/admin/hooks/useChunkDetailMergeAndDelete.ts",
        "src/features/projects/components/DocumentList.tsx",
        "src/features/projects/components/DocumentListSortableHeader.tsx",
        "src/features/projects/components/DocumentListRow.tsx",
        "src/features/projects/components/DocumentListFolderRow.tsx",
        "src/features/projects/components/DocumentListFolderRowActions.tsx",
        "src/features/projects/components/DocumentListHeaderRow.tsx",
        "src/features/projects/components/DocumentListRootDropRow.tsx",
        "src/features/projects/hooks/useDocumentListSelection.ts",
        "src/features/admin/utils/chunkGapOverlap.utils.ts",
        "src/features/admin/components/DocumentChunkView.tsx",
        "src/features/admin/components/DocumentChunkViewToolbar.tsx",
        "src/features/admin/components/DocumentChunkViewRechunkPanel.tsx",
        "src/features/admin/components/DocumentChunkViewList.tsx",
        "src/features/summary/components/ProjectSummaryTab.tsx",
        "src/features/summary/components/ProjectSummaryTabConstructifEntry.tsx",
        "src/features/summary/components/ProjectSummaryTabContrainteEntry.tsx",
        "src/features/summary/components/ProjectSummaryTabContent.tsx",
        "src/features/summary/components/ProjectSummaryTabGeneratingView.tsx",
        "src/features/summary/components/ProjectSummaryTabGate.tsx",
        "src/features/summary/components/ProjectSummaryTabNoActiveGeneration.tsx",
        "src/features/projects/components/DocumentGrid.tsx",
        "src/features/projects/components/DocumentGridRootDropCard.tsx",
        "src/features/projects/components/DocumentGridFolderCard.tsx",
        "src/features/projects/components/DocumentGridFolderCardActions.tsx",
        "src/features/projects/components/DocumentGridDocumentCard.tsx",
        "src/features/admin/components/RetrievalPlayground.tsx",
        "src/features/admin/components/RetrievalPlaygroundResultCard.tsx",
        "src/features/admin/components/RetrievalPlaygroundSearchForm.tsx",
        "src/features/admin/components/StatsOverview.tsx",
        "src/features/admin/components/StatsOverviewKpiCards.tsx",
        "src/features/admin/components/StatsOverviewQualityAlerts.tsx",
        "src/features/projects/hooks/projectHooks.ts",
        "src/features/projects/hooks/documentHooks.ts",
        "src/features/projects/hooks/documentUploadHooks.ts",
        "src/features/projects/hooks/folderHooks.ts",
      ],
      exclude: ["node_modules/", "src/test/"],
      thresholds: { lines: 90, functions: 90, branches: 85 },
    },
  },
});
