"""add structured_json to messages

Revision ID: 5432e881c108
Revises: 5ce0c89a34f0
Create Date: 2026-03-06 18:08:53.956661
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5432e881c108'
down_revision: str | None = '5ce0c89a34f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('structured_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'structured_json')
    # ### end Alembic commands ###
