"""add lot and phase to folders

Revision ID: 5ce0c89a34f0
Revises: 5ee481a6cf43
Create Date: 2026-03-05 17:10:30.608715
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ce0c89a34f0'
down_revision: str | None = '5ee481a6cf43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('lot', sa.String(length=100), server_default='', nullable=False))
    op.add_column('folders', sa.Column('phase', sa.String(length=50), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'phase')
    op.drop_column('folders', 'lot')
    # ### end Alembic commands ###
