"""add error_message chunk_count ingested_at to documents

Revision ID: 62b878a06f7f
Revises: 93a449a06b65
Create Date: 2026-04-06 10:38:36.279165
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62b878a06f7f'
down_revision: str | None = '93a449a06b65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('lot', sa.String(length=100), nullable=True))
    op.add_column('chunks', sa.Column('phase', sa.String(length=50), nullable=True))
    op.add_column('chunks', sa.Column('type', sa.String(length=100), nullable=True))
    op.add_column('chunks', sa.Column('heading_prefix', sa.Text(), nullable=True))
    op.create_index(op.f('ix_chunks_lot'), 'chunks', ['lot'], unique=False)
    op.create_index(op.f('ix_chunks_type'), 'chunks', ['type'], unique=False)
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ingested_at')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'error_message')
    op.drop_index(op.f('ix_chunks_type'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_lot'), table_name='chunks')
    op.drop_column('chunks', 'heading_prefix')
    op.drop_column('chunks', 'type')
    op.drop_column('chunks', 'phase')
    op.drop_column('chunks', 'lot')
    # ### end Alembic commands ###
