"""add project info fields

Revision ID: 72984fe8f049
Revises: b671db9f3185
Create Date: 2026-03-04 17:51:31.506991
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72984fe8f049'
down_revision: str | None = 'b671db9f3185'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('address', sa.String(length=500), server_default='', nullable=False))
    op.add_column('projects', sa.Column('client', sa.String(length=255), server_default='', nullable=False))
    op.add_column('projects', sa.Column('architect', sa.String(length=255), server_default='', nullable=False))
    op.add_column('projects', sa.Column('bureau_thermique', sa.String(length=255), server_default='', nullable=False))
    op.add_column('projects', sa.Column('bureau_vrd', sa.String(length=255), server_default='', nullable=False))
    op.add_column('projects', sa.Column('bureau_beton', sa.String(length=255), server_default='', nullable=False))
    op.add_column('projects', sa.Column('economiste', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'economiste')
    op.drop_column('projects', 'bureau_beton')
    op.drop_column('projects', 'bureau_vrd')
    op.drop_column('projects', 'bureau_thermique')
    op.drop_column('projects', 'architect')
    op.drop_column('projects', 'client')
    op.drop_column('projects', 'address')
    # ### end Alembic commands ###
