"""add_localisation_to_chunks

Revision ID: 93a449a06b65
Revises: a182250f3078
Create Date: 2026-04-03 10:47:06.421100
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '93a449a06b65'
down_revision: str | None = 'a182250f3078'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('localisation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'localisation')
    # ### end Alembic commands ###
