"""add controleur_technique to projects

Revision ID: 9c81289794d2
Revises: c044a9624592
Create Date: 2026-03-05 08:19:07.723146
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9c81289794d2'
down_revision: str | None = 'c044a9624592'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('controleur_technique', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'controleur_technique')
    # ### end Alembic commands ###
