"""add chunk metadata fields

Revision ID: a182250f3078
Revises: 00ea5b62166b
Create Date: 2026-04-03 06:26:47.398989
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a182250f3078'
down_revision: str | None = '00ea5b62166b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('content_type', sa.String(length=50), nullable=True))
    op.add_column('chunks', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('chunks', sa.Column('section_title', sa.Text(), nullable=True))
    op.add_column('chunks', sa.Column('parent_sections', sa.JSON(), nullable=True))
    op.add_column('chunks', sa.Column('char_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chunks_content_type'), 'chunks', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_content_type'), table_name='chunks')
    op.drop_column('chunks', 'char_count')
    op.drop_column('chunks', 'parent_sections')
    op.drop_column('chunks', 'section_title')
    op.drop_column('chunks', 'keywords')
    op.drop_column('chunks', 'content_type')
    # ### end Alembic commands ###
