"""add schema_json to messages

Revision ID: b75f66da6aa0
Revises: 5432e881c108
Create Date: 2026-03-07 07:53:41.352995
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b75f66da6aa0'
down_revision: str | None = '5432e881c108'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('schema_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'schema_json')
    # ### end Alembic commands ###
