"""add is_favorite to projects

Revision ID: c044a9624592
Revises: 6d9757e09967
Create Date: 2026-03-05 05:55:57.201035
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c044a9624592'
down_revision: str | None = '6d9757e09967'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_favorite')
    # ### end Alembic commands ###
